### PR TITLE
Return of .swf hitbox (#1)

### PR DESCRIPTION
**Pull request by Rosenstein**
Upload .swf file to correct directory in Default theme

### CODE REVIEW

**Comment by Rosenstein** [comment]
I've tested all this on wakachamo's 3.2.2b version.
image

**Comment by Drek282** [comment]
Thank you again.  I still need to do some work with the other themes and such.

**Comment by Rosenstein** [comment]
You are welcome.
I'd do it myself for all themes but I did not setup test environment for your fork :(

**Comment by Drek282** [comment]
Shouldn't be that difficult.  I'll try do it today.

**Comment by Drek282** [comment]
You must have a pretty relaxed php environment if you can get wakachamo to load without errors... :)

**Comment by Rosenstein** [comment]
Well, 23 year old me installed Xampp wayback in 2013 and never upgraded it, so that's why it loads :D

**Comment by Drek282** [comment]
That would explain it.  :)

**Pull request merged**
