### PR TITLE
Update basic.sql

### PR DESCRIPTION
**Pull request by Solomenka**
Add index `statdate` for `ps_plr_weapons`.

### CODE REVIEW

**Comment by Drek282** [comment]
You'll have to pardon me, I'm a bit of a git nub, so bear that in mind.  I'm also not a coder.  What is the purpose of this change?

**Comment by Drek282** [comment]
And just so it's clear, I'm grateful that you want to contribute, I just need to understand the contribution before I can merge it.

**Comment by Drek282** [comment]
You want to be able to index this table based on statdate.  Is this because current code is asking for that, but it's not there, and it's a bug, or is it because you want to add some code that will use that index?

**Comment by Drek282** [comment]
Ok...

Looking at the code, I think this is a good thing.  If it isn't, it's easy enough to revert.  Thanks for your contribution, it will be merged...

**Comment by Solomenka** [comment]
> 
> 
> And just so it's clear, I'm grateful that you want to contribute, I just need to understand the contribution before I can merge it.

Without that index awards calculation on "Weapon Class" slows down.

**Comment by Drek282** [comment]
Got it thanks.

**Comment by Solomenka** [comment]
> 
> 
> Got it thanks.

Also Perl code need to be fixed for MySQL 8.0+

**Pull request merged**
