### PR TITLE
Update basic.sql

### PR DESCRIPTION
**Pull request by Solomenka**
Some fixes for MySQL 8.0+

### CODE REVIEW

**Comment by Drek282** [comment]
Should this be changed in the PHP install version of this file as well, or not?  Will this cause problems for older versions of MySQL/MariaDB?

**Comment by Drek282** [comment]
Merged, thanks again.

**Comment by Solomenka** [comment]
> 
> 
> Should this be changed in the PHP install version of this file as well, or not? Will this cause problems for older versions of MySQL/MariaDB?

No problem for old versions and no problem for 8.0, but this is deprecated.

**Comment by Solomenka** [comment]
Query to mysql 8.0 like "CREATE TABLE `ps_map_hourly` (`statdate` date NOT NULL default '0000-00-00'..." will return an error.

**Comment by Drek282** [comment]
Got it,  thanks again.

**Comment by Drek282** [comment]
This is the kind of thing I want cleaned up, but I don't know enough to clean up myself unless it spits out an obvious error.

**Comment by Solomenka** [comment]
There will be more errors to fix with php 8 ;-)

**Comment by Drek282** [comment]
Lovely, something to look forward to...

**Comment by angelperezleon** [comment]
Nice one lads, glad PS now has some great ppl keeping this fantastic project alive as well deserved to be maiatined.
am sure StormTrooper would be proud.

**Pull request merged**
